# Generated by Django 5.2.8 on 2025-11-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('jugadores_conectados', models.IntegerField(default=0)),
            ],
        ),
    ]
